addons:
  code_climate:
    repo_token: ENV['CODECLIMATE']

language: ruby

cache: bundler

rvm:
  - 2.5.0

install:
  - bundle install

services:
  - postgresql

script:
  - bundle exec rubocop
  - bin/rails db:create
  - bin/rails db:migrate
  - bundle exec rspec spec

after_success:
  - bundle exec codeclimate-test-reporter
